const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.Keyboard,
		C3.Plugins.progressbar,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetMaxLength,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Exps.urlencode
	];
};
self.C3_JsPropNameTable = [
	{spr_SwitchMotor: 0},
	{spr_SwitchKS: 0},
	{spr_SwitchGlocke: 0},
	{spr_SwitchLicht: 0},
	{spr_SwitchRückstrahler: 0},
	{spr_SwitchRückspiegel: 0},
	{spr_SwitchSchutzBatterie: 0},
	{spr_SwitchReifen: 0},
	{spr_SwitchLoseKabel: 0},
	{spr_SwitchBremsen: 0},
	{spr_SwitchLockereTeile: 0},
	{spr_SwitchScharfkantig: 0},
	{"9ptc_HeaderBlue": 0},
	{"9patch": 0},
	{"9ptc_ButtonBlue": 0},
	{"9ptc_ButtonWhite": 0},
	{LogoTrend: 0},
	{LogoTrendWeiss: 0},
	{txt_HeaderTitel: 0},
	{txt_Start: 0},
	{txt_Infohinweis: 0},
	{txt_Aufforderung: 0},
	{"9ptc_ButtonGreen": 0},
	{txt_Tempoangaben: 0},
	{"9ptc_CheckboxWhite": 0},
	{txt_InfoKategorie: 0},
	{"9ptc_ButtonBlue2": 0},
	{txt_Version: 0},
	{txt_Prüfpositionen: 0},
	{Touch: 0},
	{txt_Berechnen: 0},
	{txt_FormularErstellen: 0},
	{spr_Back: 0},
	{input_Tempo: 0},
	{Keyboard: 0},
	{txt_DisplayKM: 0},
	{CheckGreenTret: 0},
	{CheckGreenSitz: 0},
	{txt_Gemessen: 0},
	{txt_Toleranz: 0},
	{txt_Prüfgeschwindigkeit: 0},
	{CheckGreenGewicht: 0},
	{input_Notiz: 0},
	{input_Prüftitel: 0},
	{pgb_Loader: 0},
	{txt_Versenden: 0},
	{brw_Mailto: 0},
	{JSON: 0},
	{AJAX: 0},
	{spr_ETrotti: 0},
	{spr_EScooter: 0},
	{spr_ERoller: 0},
	{spr_EBike25: 0},
	{spr_EBike45: 0},
	{spr_ELastenFR: 0},
	{spr_ECargo: 0},
	{spr_Button_ETrotti: 0},
	{spr_Button_Ebike25: 0},
	{spr_Button_EBike45: 0},
	{spr_Button_ERoller: 0},
	{spr_Button_EScooter: 0},
	{spr_Button_ELastenFR: 0},
	{spr_Button_ECargo: 0},
	{spr_Infoicon: 0},
	{txt_InfoDisclaimer: 0},
	{var_Infonote: 0},
	{speed: 0},
	{prüfgeschwindigkeit: 0},
	{toleranceMinus: 0},
	{MailText: 0},
	{MR_Motor: 0},
	{MR_Glocke: 0},
	{MR_Versicherung: 0},
	{MR_Licht: 0},
	{MR_Rueckstrahler: 0},
	{MR_Spiegel: 0},
	{MR_Batterie: 0},
	{MR_Kabel: 0},
	{MR_Reifen: 0},
	{MR_Bremsen: 0},
	{MR_Locker: 0},
	{MR_Scharf: 0},
	{var_ETrotti: 0},
	{var_ERoller: 0},
	{var_EScooter: 0},
	{var_EBike25: 0},
	{var_EBike45: 0},
	{var_ELastenFR: 0},
	{var_ECargo: 0},
	{LMF_Motor: 0},
	{LMF_Glocke: 0},
	{LMF_Versicherung: 0},
	{LMF_Licht: 0},
	{LMF_Rueckstrahler: 0},
	{LMF_Spiegel: 0},
	{LMF_Batterie: 0},
	{LMF_Kabel: 0},
	{LMF_Reifen: 0},
	{LMF_Bremsen: 0},
	{LMF_Locker: 0},
	{LMF_Scharf: 0},
	{SchnMFR_Motor: 0},
	{SchnMFR_Glocke: 0},
	{SchnMFR_Versicherung: 0},
	{SchnMFR_Licht: 0},
	{SchnMFR_Rueckstrahler: 0},
	{SchnMFR_Spiegel: 0},
	{SchnMFR_Batterie: 0},
	{SchnMFR_Kabel: 0},
	{SchnMFR_Reifen: 0},
	{SchnMFR_Bremsen: 0},
	{SchnMFR_Locker: 0},
	{SchnMFR_Scharf: 0},
	{SchwMFR_Motor: 0},
	{SchwMFR_Glocke: 0},
	{SchwMFR_Versicherung: 0},
	{SchwMFR_Licht: 0},
	{SchwMFR_Rueckstrahler: 0},
	{SchwMFR_Spiegel: 0},
	{SchwMFR_Batterie: 0},
	{SchwMFR_Kabel: 0},
	{SchwMFR_Reifen: 0},
	{SchwMFR_Bremsen: 0},
	{SchwMFR_Locker: 0},
	{SchwMFR_Scharf: 0},
	{KMR_Motor: 0},
	{KMR_Glocke: 0},
	{KMR_Versicherung: 0},
	{KMR_Licht: 0},
	{KMR_Rueckstrahler: 0},
	{KMR_Spiegel: 0},
	{KMR_Batterie: 0},
	{KMR_Kabel: 0},
	{KMR_Reifen: 0},
	{KMR_Bremsen: 0},
	{KMR_Locker: 0},
	{KMR_Scharf: 0}
];

self.InstanceType = {
	spr_SwitchMotor: class extends self.ISpriteInstance {},
	spr_SwitchKS: class extends self.ISpriteInstance {},
	spr_SwitchGlocke: class extends self.ISpriteInstance {},
	spr_SwitchLicht: class extends self.ISpriteInstance {},
	spr_SwitchRückstrahler: class extends self.ISpriteInstance {},
	spr_SwitchRückspiegel: class extends self.ISpriteInstance {},
	spr_SwitchSchutzBatterie: class extends self.ISpriteInstance {},
	spr_SwitchReifen: class extends self.ISpriteInstance {},
	spr_SwitchLoseKabel: class extends self.ISpriteInstance {},
	spr_SwitchBremsen: class extends self.ISpriteInstance {},
	spr_SwitchLockereTeile: class extends self.ISpriteInstance {},
	spr_SwitchScharfkantig: class extends self.ISpriteInstance {},
	_9ptc_HeaderBlue: class extends self.I9PatchInstance {},
	_9patch: class extends self.I9PatchInstance {},
	_9ptc_ButtonBlue: class extends self.I9PatchInstance {},
	_9ptc_ButtonWhite: class extends self.I9PatchInstance {},
	LogoTrend: class extends self.ISpriteInstance {},
	LogoTrendWeiss: class extends self.ISpriteInstance {},
	txt_HeaderTitel: class extends self.ITextInstance {},
	txt_Start: class extends self.ITextInstance {},
	txt_Infohinweis: class extends self.ITextInstance {},
	txt_Aufforderung: class extends self.ITextInstance {},
	_9ptc_ButtonGreen: class extends self.I9PatchInstance {},
	txt_Tempoangaben: class extends self.ITextInstance {},
	_9ptc_CheckboxWhite: class extends self.I9PatchInstance {},
	txt_InfoKategorie: class extends self.ITextInstance {},
	_9ptc_ButtonBlue2: class extends self.I9PatchInstance {},
	txt_Version: class extends self.ITextInstance {},
	txt_Prüfpositionen: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	txt_Berechnen: class extends self.ITextInstance {},
	txt_FormularErstellen: class extends self.ITextInstance {},
	spr_Back: class extends self.ISpriteInstance {},
	input_Tempo: class extends self.ITextInputInstance {},
	Keyboard: class extends self.IInstance {},
	txt_DisplayKM: class extends self.ITextInstance {},
	CheckGreenTret: class extends self.ISpriteInstance {},
	CheckGreenSitz: class extends self.ISpriteInstance {},
	txt_Gemessen: class extends self.ITextInstance {},
	txt_Toleranz: class extends self.ITextInstance {},
	txt_Prüfgeschwindigkeit: class extends self.ITextInstance {},
	CheckGreenGewicht: class extends self.ISpriteInstance {},
	input_Notiz: class extends self.ITextInputInstance {},
	input_Prüftitel: class extends self.ITextInputInstance {},
	pgb_Loader: class extends self.IProgressBarInstance {},
	txt_Versenden: class extends self.ITextInstance {},
	brw_Mailto: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	spr_ETrotti: class extends self.ISpriteInstance {},
	spr_EScooter: class extends self.ISpriteInstance {},
	spr_ERoller: class extends self.ISpriteInstance {},
	spr_EBike25: class extends self.ISpriteInstance {},
	spr_EBike45: class extends self.ISpriteInstance {},
	spr_ELastenFR: class extends self.ISpriteInstance {},
	spr_ECargo: class extends self.ISpriteInstance {},
	spr_Button_ETrotti: class extends self.ISpriteInstance {},
	spr_Button_Ebike25: class extends self.ISpriteInstance {},
	spr_Button_EBike45: class extends self.ISpriteInstance {},
	spr_Button_ERoller: class extends self.ISpriteInstance {},
	spr_Button_EScooter: class extends self.ISpriteInstance {},
	spr_Button_ELastenFR: class extends self.ISpriteInstance {},
	spr_Button_ECargo: class extends self.ISpriteInstance {},
	spr_Infoicon: class extends self.ISpriteInstance {},
	txt_InfoDisclaimer: class extends self.ITextInstance {}
}